command:
    db:
        priority: 40
        pull:
            base: db
            interpolate_options: false
            parse: db_packages
        push:
            base: db
            interpolate_options: false
            parse: db_packages
