command:
    backup:
        priority: 1100
        base: db
        parse: file_name

    restore:
        priority: 1105
        base: db
        confirm: true
        parse:
            file_name: false
            force:

    db:
        priority: 40

        pull:
            priority: 35
            base: db
            interpolate_options: false
            parse: db_packages
        push:
            priority: 40
            base: db
            interpolate_options: false
            parse:
                db_packages:
                db_objects:
