command:
    db:
        priority: 40

        restore:
            priority: 25
            base: db
            confirm: true
            parse:
                file_name: false
                force:
        dump:
            priority: 26
            base: db
            parse: file_name

        pull:
            priority: 35
            base: db
            interpolate_options: false
            parse: db_packages
        push:
            priority: 36
            base: db
            interpolate_options: false
            parse: db_packages
