command:
    help:
        base: environment
        priority: -5
        display_header: false
        parameters:
            command_name:
                parser: variables
                type: str
                default: []
                optional: true
                help: "space separated command name"
                value_label: NAME
                tags: [key]
        parse: command_name
    version:
        base: environment
        priority: -4
        server_enabled: true
        remote_exec: false
    test:
        base: environment
        priority: -3
        parameters:
            test_types:
                parser: variables
                type: str
                default: null
                optional: "--types"
                help: "test types"
                value_label: TYPE
                tags: [test]
            test_tags:
                parser: variables
                type: str
                default: null
                optional: "--tags"
                help: "test tags (only supported on some types)"
                value_label: TAG
                tags: [test]
            test_exclude_tags:
                parser: variables
                type: str
                default: null
                optional: "--exclude-tags"
                help: "test excluded tags (only supported on some types)"
                value_label: TAG
                tags: [test]
        parse:
            - test_types
            - test_tags
            - test_exclude_tags
    clean:
        base: environment
        priority: -1
    env:
        list:
            base: environment
            priority: 1
        get:
            base: environment
            priority: 5
            parse:
                environment_name: true
        set:
            base: environment
            priority: 10
            parse:
                environment_name:
                environment_fields:
        save:
            base: environment
            priority: 11
            parse:
                environment_name: true
                environment_fields:
        remove:
            base: environment
            priority: 20
            confirm: true
            parse:
                environment_name: true
                remove_module_path:
    host:
        resource: host
        base_name: host
        base: host
        priority: 1
