command:
    help:
        base: environment
        priority: -5
        display_header: false
        parameters:
            command_name:
                parser: variables
                type: str
                default: []
                optional: true
                help: "space separated command name"
                value_label: NAME
                tags: [key]
        parse: command_name
    version:
        base: environment
        priority: -4
        server_enabled: true
        remote_exec: false
    test:
        base: environment
        priority: -3
        parameters:
            host_name:
                parser: variable
                type: str
                default: default
                optional: true
                help: "host name for API tests"
                value_label: NAME
                tags: [host]
            disable_command:
                parser: flag
                flag: "--disable-command"
                help: "disable command tests"
                tags: [test]
            disable_api:
                parser: flag
                flag: "--disable-api"
                help: "disable API tests"
                tags: [test]
        parse:
            - host_name
            - disable_command
            - disable_api
    clean:
        base: environment
        priority: -1
    env:
        list:
            base: environment
            priority: 1
        get:
            base: environment
            priority: 5
            parse:
                environment_name: true
        set:
            base: environment
            priority: 10
            parse:
                environment_name:
                environment_fields:
        save:
            base: environment
            priority: 11
            parse:
                environment_name: true
                environment_fields:
        remove:
            base: environment
            priority: 20
            confirm: true
            parse:
                environment_name: true
                remove_module_path:
    host:
        resource: host
        base_name: host
        base: host
        priority: 1
