---
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: $ZIMAGI_BASE_IMAGE
      context: .
      sync:
        manual:
          - src: 'app/**/**/*.py'
            dest: '.'
            strip: 'app/'
          - src: 'app/scripts/*.sh'
            dest: '.'
            strip: 'app/'
          - src: 'app/zimagi-cli.py'
            dest: '.'
            strip: 'app/'
      docker:
        dockerfile: $ZIMAGI_DOCKER_FILE
        buildArgs:
          ZIMAGI_CA_KEY: "$ZIMAGI_CA_KEY"
          ZIMAGI_CA_CERT: "$ZIMAGI_CA_CERT"
          ZIMAGI_KEY: "$ZIMAGI_KEY"
          ZIMAGI_CERT: "$ZIMAGI_CERT"
          ZIMAGI_DATA_KEY: "$ZIMAGI_DATA_KEY"
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: zimagi
        chartPath: charts/charts/zimagi
        artifactOverrides:
          image: $ZIMAGI_BASE_IMAGE
        imageStrategy:
          helm: {}
portForward:
- resourceType: deployment
  resourceName: zimagi-command-api
  port: 5123
  localPort: $ZIMAGI_HOST_COMMAND_PORT
- resourceType: deployment
  resourceName: zimagi-data-api
  port: 5323
  localPort: $ZIMAGI_HOST_DATA_PORT
