# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "zimagi"
box_name: "bento/ubuntu-20.04"
user: "vagrant"
cpus: 1               # Might speedup with more cores
memory_size: 2048     # Might speedup with more memory
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
command_port: 5123         # Zimagi specific
data_port: 5323            # Zimagi specific
db_port:                   # PostgreSQL standard port 5432 (+1 to avoid conflict)
  - guest: 5432            # API database
    host: 5433
  - guest: 5433            # CLI containerized database
    host: 5434
queue_port:                # Redis standard port 6379 (+1 to avoid conflict)
  - guest: 6379            # API queue
    host: 6380
  - guest: 6380            # CLI containerized queue
    host: 6381
extra_port: []
time_zone: "America/New_York"
