# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "zimagi"
box_name: "bento/ubuntu-20.04"
user: "vagrant"
cpus: 1
memory_size: 2048
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
command_port: 5123    # No common use
data_port: 5323       # No common use
db_port: 5433         # PostgreSQL 5432 (+1 to avoid conflict)
queue_port: 6380      # Redis 6379 (+1 to avoid conflict)
http_port: 8001       # Django development HTTP 8000 (+1)
time_zone: "America/New_York"
