version: 2

volumes: &volumes
    name: Ensuring application volumes
    command: |
        mkdir -p ./data
        mkdir -p ./lib

jobs:
    test-local-commands:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Run local command tests (standard)
                command: ./scripts/reactor test command_local --init

    test-remote-commands:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Run remote command tests (standard)
                command: ./scripts/reactor test command_remote --init

    test-python-sdk:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Run API Python SDK tests (standard)
                command: ./scripts/reactor test python_sdk --init

    deploy-docker-latest:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy latest Docker image
                command: ./docker/deploy.sh standard latest

    deploy-docker-nvidia-latest:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy latest Nvidia Docker image
                command: ./docker/deploy.sh nvidia latest

    deploy-docker-version:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy versioned Docker image
                command: ./docker/deploy.sh

    deploy-docker-nvidia-version:
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy versioned Docker image
                command: ./docker/deploy.sh nvidia

    deploy-pip:
        docker:
            - image: python:3.10
        steps:
            - checkout
            - run:
                name: Copy package version
                command: cp -f ./app/VERSION ./package/VERSION

            - run:
                name: Deploy Pip package
                command: ./package/deploy.sh

    deploy-docs:
        docker:
            - image: python:3.10
        steps:
            - run:
                name: Install core dependencies
                command: |
                    apt-get update
                    apt-get install -y git g++ gcc make

            - checkout
            - run:
                name: Install documentation dependencies
                command: pip install --no-cache-dir -r ./docs/requirements.txt

            - run:
                name: Deploy documentation
                command: |
                    git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
                    git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
                    ./docs/deploy.sh git@github.com:zimagi/zimagi.git "${CIRCLE_BRANCH}"

    update-helm-chart:
        docker:
            - image: python:3.10
        steps:
            - run:
                name: Install core dependencies
                command: |
                    apt-get update
                    apt-get install -y git

            - checkout
            - run:
                name: Update Zimagi helm chart version
                command: |
                    git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
                    git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
                    ./app/deploy.sh git@github.com:zimagi/charts.git master

workflows:
    version: 2
    deploy:
        jobs:
            - test-local-commands:
                filters:
                    tags:
                        only: /.*/
            - test-remote-commands:
                filters:
                    tags:
                        only: /.*/
            - test-python-sdk:
                filters:
                    tags:
                        only: /.*/

            - deploy-docker-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - test-local-commands
                    - test-remote-commands
                    - test-python-sdk
            - deploy-docker-nvidia-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - test-local-commands
                    - test-remote-commands
                    - test-python-sdk

            - deploy-docker-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-local-commands
                    - test-remote-commands
                    - test-python-sdk
            - deploy-docker-nvidia-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-local-commands
                    - test-remote-commands
                    - test-python-sdk

            - deploy-pip:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-local-commands
                    - test-remote-commands
                    - test-python-sdk

            - deploy-docs:
                filters:
                    branches:
                        only:
                            - main
                            - docs

            - update-helm-chart:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-version
                    - deploy-docker-nvidia-version
