version: 2

volumes: &volumes
    name: Ensuring application volumes
    command: |
        mkdir -p ./data
        mkdir -p ./lib

jobs:
    deploy-docker-latest:
        machine: true
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy latest Docker image
                command: ./build/docker/deploy_latest.sh

    deploy-docker-version:
        machine: true
        steps:
            - checkout
            - run: *volumes
            - run:
                name: Deploy versioned Docker image
                command: ./build/docker/deploy_version.sh

    deploy-pip:
        docker:
            - image: python:3.8
        steps:
            - checkout
            - run:
                name: Deploy Pip package
                command: ./build/pip/deploy.sh

    deploy-docs:
        docker:
            - image: python:3.8
        steps:
            - run:
                name: Install core dependencies
                command: |
                    apt-get update
                    apt-get install -y git g++ gcc make

            - checkout

            - run:
                name: Install documentation dependencies
                command: pip install --no-cache-dir -r ./docs/requirements.txt

            - run:
                name: Deploy documentation
                command: |
                    git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
                    git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
                    ./build/docs/deploy.sh git@github.com:zimagi/zimagi.git "${CIRCLE_BRANCH}"

workflows:
    version: 2
    deploy:
        jobs:
            - deploy-docker-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
            - deploy-docker-version:
                filters:
                    tags:
                        only: /^.*/
                    branches:
                        ignore: /.*/
            - deploy-pip:
                filters:
                    tags:
                        only: /^.*/
                    branches:
                        ignore: /.*/
            - deploy-docs:
                filters:
                    branches:
                        only:
                            - main
                            - docs
