hostname: zimagi
cpus: 2
memory_size: 7168

copy_ssh_keys: false
copy_gitconfig: false
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false

ports: # HostPort: AppName.ServiceName.Environment:PortName
  5432: zimagi.postgresql.default:5432/tcp
  6379: zimagi.redis.default:6379/tcp
  5123: zimagi.command-api.default:5000/tcp
  5323: zimagi.data-api.default:5000/tcp
  5555: zimagi.flower.default:5000/tcp
