config:
    overview: |
        Manage environment configurations

    description: |
        TODO

    list:
        overview: |
            List configurations in current environment

        description: |
            TODO

    get:
        overview: |
            Get environment configuration value

        description: |
            TODO

    save:
        overview: |
            Save environment configuration value

        description: |
            TODO

    remove:
        overview: |
            Remove an existing environment configuration

        description: |
            TODO

    clear:
        overview: |
            Clear all existing environment configurations

        description: |
            TODO
