config:
    overview: |
        Manage environment configurations

    description: |
        Manage environment configurations

    list:
        overview: |
            List configurations in current environment

        description: |
            List configurations in current environment

    get:
        overview: |
            Get environment configuration value

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pulvinar nisl ac magna ultricies dignissim. Praesent eu feugiat elit. Cras porta magna vel blandit euismod.

        description: |
            Get environment configuration value

    save:
        overview: |
            Save environment configuration value

        description: |
            Save environment configuration value

    remove:
        overview: |
            Remove an existing environment configuration

        description: |
            Remove an existing environment configuration

    clear:
        overview: |
            Clear all existing environment configurations

        description: |
            Clear all existing environment configurations
