version:
    overview: |
        (local) Get client and environment versions

    description: |
        (local) Get client and environment versions

clean:
    overview: |
        (local) Clean application Docker images

    description: |
        (local) Clean application Docker images

env:
    overview: |
        (local) Manage environments

    description: |
        (local) Manage environments

    get:
        overview: |
            (local) Get existing environment

        description: |
            (local) Get existing environment

    set:
        overview: |
            (local) Set active environment

        description: |
            (local) Set active environment

    save:
        overview: |
            (local) Update an existing environment

        description: |
            (local) Update an existing environment

    remove:
        overview: |
            (local) Remove an existing environment

        description: |
            (local) Remove an existing environment

host:
    overview: |
        (local) Manage environment hosts

    description: |
        (local) Manage environment hosts

    list:
        overview: |
            (local) List environment hosts

        description: |
            (local) List environment hosts

    get:
        overview: |
            (local) Get existing environment host

        description: |
            (local) Get existing environment host

    save:
        overview: |
            (local) Save environment host

        description: |
            (local) Save environment host

    remove:
        overview: |
            (local) Remove an existing environment host

        description: |
            (local) Remove an existing environment host

    clear:
        overview: |
            (local) Clear all environment hosts

        description: |
            (local) Clear all environment hosts
