version:
    overview: |
        (local) Get client and environment versions

    description: |
        TODO

clean:
    overview: |
        (local) Clean application Docker images

    description: |
        TODO

env:
    overview: |
        (local) Manage environments

    description: |
        TODO

    get:
        overview: |
            (local) Get existing environment

        description: |
            TODO

    set:
        overview: |
            (local) Set active environment

        description: |
            TODO

    save:
        overview: |
            (local) Update an existing environment

        description: |
            TODO

    remove:
        overview: |
            (local) Remove an existing environment

        description: |
            TODO

host:
    overview: |
        (local) Manage environment hosts

    description: |
        TODO

    list:
        overview: |
            (local) List environment hosts

        description: |
            TODO

    get:
        overview: |
            (local) Get existing environment host

        description: |
            TODO

    save:
        overview: |
            (local) Save environment host

        description: |
            TODO

    remove:
        overview: |
            (local) Remove an existing environment host

        description: |
            TODO

    clear:
        overview: |
            (local) Clear all environment hosts

        description: |
            TODO
