version:
    overview: |
        (local) Get client and environment versions

    description: |
        (local) Get client and environment versions

	Returns the versions of both client and environment 

clean:
    overview: |
        (local) Clean application Docker images

    description: |
        Clean application Docker images

env:
    overview: |
        (local) Manage environments

    description: |
        (local) Manage environments

	Commands let you manage the current active environment. You can get the existing environment, set the active environment, update an existing environment, and remove an existing environment.

    get:
        overview: |
            (local) Get existing environment

        description: |
	    (local) Get existing environment
	    Gets the currently active environment, returning details about the environment such as the environment’s status, base image, runtime image, attached hosts, and included modules.

    set:
        overview: |
            (local) Set active environment

        description: |
	    (local) Set active environment
            Sets the currently active environment. Takes``environment_name`` - The name of a valid Zimagi environment.

    save:
        overview: |
            (local) Update an existing environment

        description: |
            (local) Update an existing environment
	    Assigns and saves attributes of the current environment. Takes ``field=Value``, where ``field``s are one of the following ``repo``, ``base_image``, ``runtime_image``, and ``Value`` is a string.

    remove:
        overview: |
            (local) Remove an existing environment

        description: |
            (local) Remove an existing environment
	    Removes the current environment from the Zimagi installation.

host:
    overview: |
        (local) Manage environment hosts

    description: |
        (local) Manage environment hosts

	Host commands let you interact with hosts tied to the current environment. Find active hosts, modify hosts, and remove hosts.

    list:
        overview: |
            (local) List environment hosts

        description: |
            (local) List environment hosts

	    Returns a list of all hosts mapped to the current local environment.

    get:
        overview: |
            (local) Get existing environment host

        description: |
            (local) Get existing environment host

	    Get information about a specific host in the current environment. Takes ``host_name`` - The
name of a host in the environment. If none is provided, defaults to ``@host_name|default.``

    save:
        overview: |
            (local) Save environment host

        description: |
            (local) Save environment host

	    Add and save a new environment host. Takes ``field=Value`` - Key-value pairs specifying host configurations. Requires Key-value pair for ``host=URL``. Optional Key-value pairs - ``port``, ``user``,``token``.

    remove:
        overview: |
            (local) Remove an existing environment host

        description: |
            (local) Remove an existing environment host


    clear:
        overview: |
            (local) Clear all environment hosts

        description: |
            (local) Clear all environment hosts

	    Remove all hosts from the current environment. Takes one or more search queries.



