service:
    overview: |
        Manage local Zimagi services

    description: |
        Zimagi runs local services in the background to provide full application capabilities even when not run in API mode

    list:
        overview: |
            List all available local Zimagi services with their status

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    get:
        overview: |
            Get the specification and status for a local Zimagi service

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    start:
        overview: |
            Start one or more local Zimagi services

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    restart:
        overview: |
            Restart one or more local Zimagi services

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    shell:
        overview: |
            Log into a running local Zimagi service container

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    stop:
        overview: |
            Stop one or more running local Zimagi service containers

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    destroy:
        overview: |
            Stop and destroy one or more running local Zimagi service containers

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api

    logs:
        overview: |
            Display log entries for one or more local Zimagi service containers

        description: |
            Core services available: postgresql, redis, scheduler, worker, command-api, data-api
