
_zimagi: &zimagi
    image: "@ZIMAGI_RUNTIME_IMAGE"
    wait: 3
    inherit_environment: true
    environment:
        ZIMAGI_POSTGRES_HOST: pgbouncer
        ZIMAGI_POSTGRES_PORT: 6432
        ZIMAGI_REDIS_HOST: redis
        ZIMAGI_REDIS_PORT: 6379
    volumes:
        "@ZIMAGI_HOST_APP_DIR":
            bind: /usr/local/share/zimagi
            mode: rw
        "@ZIMAGI_HOST_DATA_DIR":
            bind: /var/local/zimagi
            mode: rw
        "@ZIMAGI_HOST_LIB_DIR":
            bind: /usr/local/lib/zimagi
            mode: rw

services:
    postgresql:
        image: postgres:14-bullseye
        wait: 1
        command: "postgres -c 'max_connections=@ZIMAGI_POSTGRES_SERVICE_CONNECTIONS<< 100 >>'"
        memory: "@ZIMAGI_POSTGRES_SERVICE_MEMORY<< 1g >>"
        environment:
            POSTGRES_USER: "@ZIMAGI_POSTGRES_USER"
            POSTGRES_PASSWORD: "@ZIMAGI_POSTGRES_PASSWORD"
            POSTGRES_DB: "@ZIMAGI_POSTGRES_DB"
        volumes:
            postgresql:
                bind: /var/lib/postgresql
                mode: rw

    pgbouncer:
        requires: postgresql
        image: bitnami/pgbouncer:1.16.1
        wait: 1
        memory: "@ZIMAGI_PGBOUNCER_SERVICE_MEMORY<< 250m >>"
        environment:
            POSTGRESQL_HOST: postgresql
            POSTGRESQL_PORT: 5432
            POSTGRESQL_USERNAME: "@ZIMAGI_POSTGRES_USER"
            POSTGRESQL_PASSWORD: "@ZIMAGI_POSTGRES_PASSWORD"
            POSTGRESQL_DATABASE: "@ZIMAGI_POSTGRES_DB"
            PGBOUNCER_DATABASE: "@ZIMAGI_POSTGRES_DB"
            PGBOUNCER_PORT: 6432
            PGBOUNCER_POOL_MODE: transaction
            PGBOUNCER_MAX_DB_CONNECTIONS: "@ZIMAGI_POSTGRES_SERVICE_CONNECTIONS<< 100 >>"
            PGBOUNCER_MAX_CLIENT_CONN: "@ZIMAGI_PGBOUNCER_SERVICE_CONNECTIONS<< 1000 >>"
            PGBOUNCER_DEFAULT_POOL_SIZE: "@ZIMAGI_PGBOUNCER_SERVICE_POOL_SIZE<< 100 >>"
        ports:
            6432/tcp: "@ZIMAGI_POSTGRES_HOST_PORT"

    redis:
        image: redis:6-bullseye
        wait: 1
        command: "redis-server --requirepass @ZIMAGI_REDIS_PASSWORD"
        memory: "@ZIMAGI_REDIS_SERVICE_MEMORY<< 900m >>"
        ports:
            6379/tcp: "@ZIMAGI_REDIS_HOST_PORT"
        volumes:
            redis:
                bind: /data
                mode: rw

    celery:
        image: "@ZIMAGI_RUNTIME_IMAGE"
        entrypoint: celery-flower
        wait: 0
        memory: "@ZIMAGI_CELERY_FLOWER_SERVICE_MEMORY<< 250m >>"
        inherit_environment: true
        environment:
            ZIMAGI_POSTGRES_HOST: pgbouncer
            ZIMAGI_POSTGRES_PORT: 6432
            ZIMAGI_REDIS_HOST: redis
            ZIMAGI_REDIS_PORT: 6379
        ports:
            5000/tcp: "@ZIMAGI_CELERY_FLOWER_HOST_PORT"
        requires:
            - redis

    scheduler:
        <<: *zimagi
        wait: 6
        entrypoint: zimagi-scheduler
        memory: "@ZIMAGI_SCHEDULER_SERVICE_MEMORY<< 250m >>"
        requires:
            - pgbouncer
            - redis

    worker:
        <<: *zimagi
        requires: scheduler
        runtime: "@ZIMAGI_DOCKER_RUNTIME"
        entrypoint: zimagi-worker
        memory: "@ZIMAGI_WORKER_SERVICE_MEMORY<< 1g >>"

    command-api:
        <<: *zimagi
        requires: scheduler
        runtime: "@ZIMAGI_DOCKER_RUNTIME"
        entrypoint: zimagi-command
        memory: "@ZIMAGI_COMMAND_SERVICE_MEMORY<< 1g >>"
        ports:
            5000/tcp: "@ZIMAGI_HOST_COMMAND_PORT"

    data-api:
        <<: *zimagi
        requires: scheduler
        entrypoint: zimagi-data
        memory: "@ZIMAGI_DATA_SERVICE_MEMORY<< 1g >>"
        ports:
            5000/tcp: "@ZIMAGI_HOST_DATA_PORT"
